version: "3"
services:
  cuda:
    build: .
    working_dir: /src
    command: ["make", "test"]
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ./:/src
